# Configuration for Dependabot to automatically update dependencies in the project.
---
version: 2
updates:
    # Update Bun dependencies in the root directory and all packages.
    - package-ecosystem: bun
      target-branch: development
      directories:
          - /
          - /apps/api
          - /apps/docs
          - /packages/lib
          - /packages/resource-pack
      schedule:
          interval: monthly
          timezone: Europe/Warsaw
      open-pull-requests-limit: 40
      labels:
          - "deps"
          - "deps/bun"
      commit-message:
          prefix: "chore(bun):"
    # Update GitHub Actions workflows in the root directory and all packages.
    - package-ecosystem: github-actions
      target-branch: development
      directory: /
      schedule:
          interval: monthly
          timezone: Europe/Warsaw
      open-pull-requests-limit: 10
      labels:
          - "deps"
          - "deps/actions"
      commit-message:
          prefix: "chore(workflows):"
    # Update Docker image in the documentation application.
    - package-ecosystem: docker
      directories:
          - /apps/api
          - /apps/docs
      schedule:
          interval: monthly
          timezone: Europe/Warsaw
      open-pull-requests-limit: 10
      labels:
          - "deps"
          - "deps/docker"
      commit-message:
          prefix: "chore(docker):"
    - package-ecosystem: docker-compose
      directories:
          - /apps/api
          - /apps/docs
      schedule:
          interval: monthly
          timezone: Europe/Warsaw
      open-pull-requests-limit: 10
      labels:
          - "deps"
          - "deps/docker-compose"
      commit-message:
          prefix: "chore(docker-compose):"
