#!/bin/bash
# This file is being executed before every single commit.

bunx lint-staged
(
    cd apps
    (
        cd docs
        bunx lint-staged
    )
)
(
    cd packages
    (
        cd lib
        bunx lint-staged
    )
    (
        cd resource-pack
        bunx lint-staged
    )
)
