#!/bin/bash
# This file is being executed before pushing via git.

bun run format:check
(
    cd apps
    (
        cd docs
        bun run format:check
        bun run lint:fix
    )
)
(
    cd packages
    (
        cd lib
        bun run format:check
        bun run lint:fix
    )
    (
        cd resource-pack
        bun run format:check
        bun run lint:fix
    )
)
